### ISSUE TITLE
Upload to Modrinth is broken

### ISSUE THREAD

**Issue by jackassmc** [TerraformersMC/GradleScripts#6]
It used to fail with ```Caused by: java.lang.NullPointerException: Cannot invoke "com.modrinth.minotaur.responses.ResponseError.getError()" because "this.errorInfo" is null```, see https://github.com/TerraformersMC/ModMenu/runs/7184056650?check_suite_focus=true#step%3A8%3A161=

Now it fails with ```Caused by: org.gradle.api.GradleException: Upload failed! Status: 401 Reason: Authentication Error: Error while communicating to GitHub OAuth2: error decoding response body: missing field `login` at line 1 column 80```, see https://github.com/TerraformersMC/ModMenu/runs/7296382376?check_suite_focus=true#step%3A8%3A187=

**Comment by jackassmc** [comment]
This seems to be caused by an invalid MODRINTH_TOKEN. @Prospector could you please update it?

**Comment by Prospector** [comment]
Will do later today

**Comment by Prospector** [comment]
I've added the token

**Comment by jackassmc** [comment]
Fixed, see https://github.com/TerraformersMC/ModMenu/actions/runs/2665493171. Thanks!
