### ISSUE TITLE
Modrinth and Curseforge token invalid

### ISSUE THREAD

**Issue by jackassmc** [TerraformersMC/GradleScripts#8]
Ping @Prospector

**Comment by Prospector** [comment]
I've updated the Modrinth token, I don't think the CF one can be invalid though. I am confused though, as the latest release 5.0.1 seems to have published correctly across all platforms?

**Comment by jackassmc** [comment]
Thanks! I believe Curseforge needs to be updated too, because the release action only succeeded after adding my own Curseforge and Modrinth tokens:
- The first build failed because of Curseforge: https://github.com/TerraformersMC/ModMenu/actions/runs/3644055436/jobs/6152900976 
- The second one because of Modrinth: https://github.com/TerraformersMC/ModMenu/actions/runs/3644260367/jobs/6153327829
